import type {
  NormalizedCampsite,
  Alert,
  Booking,
  Message,
} from "@camper/shared-types";

export const sampleCampsites: NormalizedCampsite[] = [
  {
    id: "cs-001",
    campgroundId: "cg-001",
    campgroundName: "Upper Pines Campground",
    externalId: "232447",
    platform: "recreation_gov",
    name: "Site 42 — Riverside",
    description:
      "Spacious tent site along the Merced River with stunning views of Half Dome. Mature pine canopy provides ample shade.",
    siteType: "tent",
    maxOccupancy: 6,
    amenities: [
      "Fire ring",
      "Picnic table",
      "Bear box",
      "Potable water",
      "Flush toilets",
    ],
    pricePerNight: 36,
    currency: "USD",
    imageUrls: [
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800",
    ],
    latitude: 37.7386,
    longitude: -119.5658,
    region: "Yosemite Valley",
    country: "US",
    available: true,
    availableDates: ["2026-07-15", "2026-07-16", "2026-07-17", "2026-07-18"],
    bookingUrl: "https://www.recreation.gov/camping/campsites/232447",
  },
  {
    id: "cs-002",
    campgroundId: "cg-002",
    campgroundName: "North Pines Campground",
    externalId: "232450",
    platform: "recreation_gov",
    name: "Site 118 — Walk-in",
    description:
      "Secluded walk-in tent site near Mirror Lake trailhead. Quieter location, perfect for backpackers.",
    siteType: "tent",
    maxOccupancy: 4,
    amenities: ["Fire ring", "Picnic table", "Bear box", "Potable water"],
    pricePerNight: 36,
    currency: "USD",
    imageUrls: [
      "https://images.unsplash.com/photo-1532339142463-fd0a8979791a?w=800",
    ],
    latitude: 37.7452,
    longitude: -119.5583,
    region: "Yosemite Valley",
    country: "US",
    available: false,
    availableDates: [],
    bookingUrl: null,
  },
  {
    id: "cs-003",
    campgroundId: "cg-003",
    campgroundName: "Two Jack Lakeside Campground",
    externalId: "TJ-201",
    platform: "parks_canada",
    name: "Lakeside 15 — Premium",
    description:
      "Premium waterfront site on Two Jack Lake with mountain panorama. OTENTik equipped site with raised platform.",
    siteType: "glamping",
    maxOccupancy: 6,
    amenities: [
      "Fire ring",
      "Picnic table",
      "Bear bin",
      "Lake access",
      "OTENTik shelter",
    ],
    pricePerNight: 120,
    currency: "CAD",
    imageUrls: [
      "https://images.unsplash.com/photo-1537905569824-f89f14cceb68?w=800",
    ],
    latitude: 51.2159,
    longitude: -115.4244,
    region: "Banff National Park",
    country: "CA",
    available: true,
    availableDates: ["2026-08-01", "2026-08-02", "2026-08-03"],
    bookingUrl: "https://reservation.pc.gc.ca/",
  },
  {
    id: "cs-004",
    campgroundId: "cg-004",
    campgroundName: "Wawona Campground",
    externalId: "232452",
    platform: "recreation_gov",
    name: "Loop B — Site 55 RV",
    description:
      "Full hookup RV site near the Mariposa Grove of Giant Sequoias. Level pad, great for larger rigs.",
    siteType: "rv",
    maxOccupancy: 8,
    amenities: [
      "Electric hookup",
      "Water hookup",
      "Sewer hookup",
      "Picnic table",
      "Fire ring",
      "Dump station",
    ],
    pricePerNight: 50,
    currency: "USD",
    imageUrls: [
      "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800",
    ],
    latitude: 37.5368,
    longitude: -119.6567,
    region: "Yosemite South",
    country: "US",
    available: true,
    availableDates: ["2026-06-20", "2026-06-21", "2026-06-22"],
    bookingUrl: "https://www.recreation.gov/camping/campsites/232452",
  },
];

export const sampleAlerts: Alert[] = [
  {
    id: "al-001",
    userId: "user-001",
    campgroundId: "cg-002",
    campgroundName: "North Pines Campground",
    platform: "recreation_gov",
    startDate: "2026-07-20",
    endDate: "2026-07-23",
    siteTypes: ["tent"],
    autoBook: false,
    confirmFirst: true,
    status: "active",
    scanIntervalMs: 300_000,
    lastScannedAt: new Date("2026-02-20T10:30:00Z"),
    triggeredAt: null,
    createdAt: new Date("2026-02-18T08:00:00Z"),
    updatedAt: new Date("2026-02-20T10:30:00Z"),
  },
  {
    id: "al-002",
    userId: "user-001",
    campgroundId: "cg-003",
    campgroundName: "Two Jack Lakeside Campground",
    platform: "parks_canada",
    startDate: "2026-08-10",
    endDate: "2026-08-14",
    siteTypes: ["glamping", "tent"],
    autoBook: true,
    confirmFirst: true,
    status: "active",
    scanIntervalMs: 300_000,
    lastScannedAt: new Date("2026-02-20T10:28:00Z"),
    triggeredAt: null,
    createdAt: new Date("2026-02-15T14:00:00Z"),
    updatedAt: new Date("2026-02-20T10:28:00Z"),
  },
];

export const sampleBookings: Booking[] = [
  {
    id: "bk-001",
    userId: "user-001",
    alertId: null,
    campsiteId: "cs-001",
    campsiteName: "Site 42 — Riverside",
    campgroundName: "Upper Pines Campground",
    platform: "recreation_gov",
    externalBookingId: "RG-2026-88421",
    startDate: "2026-07-15",
    endDate: "2026-07-18",
    totalCost: 108,
    currency: "USD",
    status: "confirmed",
    bookingUrl: "https://www.recreation.gov/camping/campsites/232447",
    createdAt: new Date("2026-02-10T09:15:00Z"),
    updatedAt: new Date("2026-02-10T09:15:00Z"),
  },
  {
    id: "bk-002",
    userId: "user-001",
    alertId: null,
    campsiteId: "cs-004",
    campsiteName: "Loop B — Site 55 RV",
    campgroundName: "Wawona Campground",
    platform: "recreation_gov",
    externalBookingId: "RG-2025-77210",
    startDate: "2025-09-01",
    endDate: "2025-09-04",
    totalCost: 150,
    currency: "USD",
    status: "confirmed",
    bookingUrl: "https://www.recreation.gov/camping/campsites/232452",
    createdAt: new Date("2025-08-15T11:00:00Z"),
    updatedAt: new Date("2025-08-15T11:00:00Z"),
  },
];

export const sampleMessages: Message[] = [
  {
    id: "msg-001",
    conversationId: "conv-001",
    role: "assistant",
    content:
      "Welcome to Camper! I can help you find and book campsites, set up availability alerts, and plan your next outdoor adventure. What would you like to do?",
    richContent: null,
    toolCalls: null,
    toolResults: null,
    createdAt: new Date("2026-02-20T08:00:00Z"),
  },
];
